### ISSUE TITLE
go build 不过

### ISSUE THREAD

**Issue by or0or1** [vbenjs/gf-vben#2]
# github.com/vance-liu/gdb-adapter
/root/go/pkg/mod/github.com/vance-liu/gdb-adapter@v0.0.0-20210417015145-03ed4fb0d987/adapter.go:96:5: unknown field 'LinkInfo' in struct literal of type gdb.ConfigNode

**Comment by memoryDemo** [comment]
> # github.com/vance-liu/gdb-adapter
> /root/go/pkg/mod/github.com/vance-liu/gdb-adapter@v0.0.0-20210417015145-03ed4fb0d987/adapter.go:96:5: unknown field 'LinkInfo' in struct literal of type gdb.ConfigNode

升级下版本 V0.2.0
