### ISSUE TITLE
配置文件样例中不应包含真实服务器的信息

### ISSUE THREAD

**Issue by huhuegg** [vbenjs/gf-vben#3]
config.toml文件暴露了mysql数据库的信息，端口外放，认证通过可直接访问mysql用户数据，建议收敛～
从服务端逻辑能看到对用户密码仅做了md5，并直接写入数据库，这样mysql的用户信息就呵呵了，建议在配置文件中预留可配置的对称加密密钥，配置样例中仅描述，强烈不使用线上配置提交git

**Comment by SnoW-Wei** [comment]
不太严谨，我本来也想发issues提提醒下作者。 
我看已经有人留言了，我在这留言提示下。

**Comment by wx-11** [comment]
不太懂 md5不是不可逆吗 有什么问题吗 大佬们指点一下可以不 刚入门
